// src/components/wizard/ChannelCard.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { ChannelConfig, ChannelOption } from '@/utils/channel-types'
import { getChannelOptionName, getChannelOptionDescription, getChannelConfigFieldLabel, getChannelConfigFieldPlaceholder } from '@/utils/channel-types'
import { useI18nStore } from '@/stores/i18n'
import { Globe, MessageCircle, Send, Zap, Phone, MessageSquare, Hash } from 'lucide-vue-next'

const props = defineProps<{
  channel: ChannelConfig
  channelOption: ChannelOption
}>()

const emit = defineEmits<{
  (e: 'toggle', id: string, enabled: boolean): void
  (e: 'update:config', id: string, field: string, value: any): void
}>()

const { t, language } = useI18nStore()

const iconComponent = computed(() => {
  const icons: Record<string, any> = {
    globe: Globe,
    'message-circle': MessageCircle,
    send: Send,
    zap: Zap,
    phone: Phone,
    'message-square': MessageSquare,
    hash: Hash
  }
  return icons[props.channelOption.icon] || Globe
})

const hasLogo = computed(() => !!props.channelOption.logo)

function handleToggle(e: Event) {
  const target = e.target as HTMLInputElement
  emit('toggle', props.channel.id, target.checked)
}

function handleConfigChange(field: string, e: Event) {
  const target = e.target as HTMLInputElement
  emit('update:config', props.channel.id, field, target.value)
}
</script>

<template>
  <div class="channel-card card-apple">
    <div class="channel-header">
      <div class="channel-info">
        <div class="channel-icon" :style="{ backgroundColor: channelOption.color }">
          <img v-if="hasLogo" :src="channelOption.logo" class="channel-logo" :alt="getChannelOptionName(channelOption, language)" />
          <component v-else :is="iconComponent" class="icon" />
        </div>
        <div class="channel-text">
          <h3 class="channel-name">{{ getChannelOptionName(channelOption, language) }}</h3>
          <p class="channel-desc">{{ getChannelOptionDescription(channelOption, language) }}</p>
          <a 
            v-if="channelOption.helpUrl" 
            :href="channelOption.helpUrl" 
            target="_blank" 
            class="help-link"
          >
            {{ t.channelHelpLink }}
          </a>
        </div>
      </div>
      <label class="toggle">
        <input 
          type="checkbox" 
          :checked="channel.enabled" 
          @change="handleToggle"
        />
        <span class="toggle-slider"></span>
      </label>
    </div>
    
    <div v-if="channel.enabled && channelOption.configFields.length > 0" class="channel-config">
      <div 
        v-for="field in channelOption.configFields" 
        :key="field.name" 
        class="config-field"
      >
        <label class="field-label">{{ getChannelConfigFieldLabel(field, language) }}</label>
        <input
          :type="field.type"
          class="field-input"
          :value="channel.config[field.name] || ''"
          :placeholder="getChannelConfigFieldPlaceholder(field, language)"
          @input="handleConfigChange(field.name, $event)"
        />
      </div>
    </div>
  </div>
</template>

<style scoped>
.channel-card {
  padding: 16px;
}

.channel-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.help-link {
  font-size: 12px;
  color: var(--accent-blue);
  text-decoration: none;
  margin-top: 4px;
  display: inline-block;
}

.help-link:hover {
  text-decoration: underline;
}

.channel-info {
  display: flex;
  align-items: center;
  gap: 12px;
}

.channel-icon {
  width: 44px;
  height: 44px;
  border-radius: 12px;
  display: flex;
  align-items: center;
  justify-content: center;
  color: white;
  overflow: hidden;
}

.channel-logo {
  width: 28px;
  height: 28px;
  object-fit: contain;
}

.icon {
  width: 22px;
  height: 22px;
}

.channel-name {
  font-size: 16px;
  font-weight: 600;
  color: var(--text-primary);
  margin-bottom: 4px;
}

.channel-desc {
  font-size: 13px;
  color: var(--text-tertiary);
}

.toggle {
  position: relative;
  display: inline-block;
  width: 48px;
  height: 28px;
}

.toggle input {
  opacity: 0;
  width: 0;
  height: 0;
}

.toggle-slider {
  position: absolute;
  cursor: pointer;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-color: var(--border-color);
  transition: 0.3s;
  border-radius: 28px;
}

.toggle-slider:before {
  position: absolute;
  content: "";
  height: 22px;
  width: 22px;
  left: 3px;
  bottom: 3px;
  background-color: white;
  transition: 0.3s;
  border-radius: 50%;
}

.toggle input:checked + .toggle-slider {
  background-color: var(--accent-blue);
}

.toggle input:checked + .toggle-slider:before {
  transform: translateX(20px);
}

.channel-config {
  margin-top: 16px;
  padding-top: 16px;
  border-top: 1px solid var(--border-color);
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.field-label {
  display: block;
  font-size: 13px;
  font-weight: 500;
  color: var(--text-secondary);
  margin-bottom: 6px;
}

.field-input {
  width: 100%;
  padding: 10px 14px;
  background: var(--bg-primary);
  border: 1px solid var(--border-color);
  border-radius: 10px;
  color: var(--text-primary);
  font-size: 14px;
  outline: none;
  transition: border-color 0.2s;
}

.field-input:focus {
  border-color: var(--accent-blue);
}

.field-input::placeholder {
  color: var(--text-tertiary);
}
</style>

// src/components/ChannelCard.tsx
'use client'

import { useState } from 'react'
import { ChannelConfig, ChannelOption, getChannelOptionName, getChannelOptionDescription, getChannelConfigFieldLabel, getChannelConfigFieldPlaceholder } from '@/lib/channel-types'
import { Check, Send, MessageSquare, Zap, MessageCircle, Globe, Eye, EyeOff, Play, Loader2, Info } from 'lucide-react'
import { ChannelDebugger, DebugResult } from '@/lib/channel-debugger'
import { useI18n } from '@/lib/i18n-context'

interface ChannelCardProps {
  channel: ChannelConfig
  channelOption: ChannelOption
  onToggle: (id: string, enabled: boolean) => void
  onConfigChange: (id: string, field: string, value: string) => void
  showDetails?: boolean
  onTestResult?: (channelId: string, result: DebugResult) => void
}

export function ChannelCard({ 
  channel, 
  channelOption, 
  onToggle, 
  onConfigChange, 
  showDetails = true,
  onTestResult
}: ChannelCardProps) {
  const { t, isLanguageLoaded, language } = useI18n()
  const [isTesting, setIsTesting] = useState(false)
  const [testResult, setTestResult] = useState<DebugResult | null>(null)
  const [showGuide, setShowGuide] = useState(false)

  const getChannelIcon = () => {
    switch (channelOption.id) {
      case 'dingtalk': return MessageCircle
      case 'telegram': return Send
      case 'feishu': return Zap
      case 'web': return Globe
      default: return MessageCircle
    }
  }

  const Icon = getChannelIcon()
  
  const testChannel = async () => {
    if (!channel.enabled) return
    
    setIsTesting(true)
    setTestResult(null)
    
    try {
      const result = await ChannelDebugger.testChannel(channel, language)
      setTestResult(result)
      if (onTestResult) {
        onTestResult(channel.id, result)
      }
    } catch (error) {
      const result = { success: false, message: `测试失败: ${(error as Error).message}` }
      setTestResult(result)
      if (onTestResult) {
        onTestResult(channel.id, result)
      }
    } finally {
      setIsTesting(false)
    }
  }

  const guideContent = ChannelDebugger.getSetupGuide(channel.id, language)

  if (!isLanguageLoaded) {
    return null
  }

  const channelName = getChannelOptionName(channelOption, language)
  const channelDesc = getChannelOptionDescription(channelOption, language)

  return (
    <div 
      className={`p-4 card-apple border rounded-2xl transition-all ${
        channel.enabled 
          ? 'border-[#0A84FF] bg-[#f5f5f7]' 
          : 'border-[#d2d2d7]'
      }`}
    >
      <div className="flex items-center justify-between">
        <div 
          className="flex items-center gap-3 cursor-pointer flex-1"
          onClick={() => onToggle(channel.id, !channel.enabled)}
        >
          <div 
            className={`w-10 h-10 rounded-xl flex items-center justify-center ${
              channel.enabled 
                ? 'bg-[#0A84FF]' 
                : 'bg-[#e5e5e7]'
            }`}
          >
            <Icon className={`w-5 h-5 ${
              channel.enabled ? 'text-white' : 'text-[#86868b]'
            }`} />
          </div>
          <div className="flex-1">
            <div className="font-medium text-[#1d1d1f]">
              {channelName}
            </div>
            <div className="text-xs text-[#6e6e73]">
              {channelDesc}
            </div>
          </div>
          <div className="flex items-center gap-2">
            {guideContent && (
              <button
                onClick={(e) => {
                  e.stopPropagation()
                  setShowGuide(!showGuide)
                }}
                className="p-1 rounded-md hover:bg-[#e5e5e7] transition-colors"
              >
                <Info className="w-4 h-4 text-[#86868b]" />
              </button>
            )}
            <div className={`relative w-10 h-6 flex items-center ${
              channel.enabled ? 'justify-end pr-1' : 'justify-start pl-1'
            }`}>
              <div 
                className={`w-4 h-4 rounded-full transition-colors ${
                  channel.enabled 
                    ? 'bg-white' 
                    : 'bg-[#aeaeb2]'
                }`}
              />
              <div 
                className={`absolute w-8 h-6 rounded-full transition-colors ${
                  channel.enabled 
                    ? 'bg-[#34C759]' 
                    : 'bg-[#d1d1d6]'
                }`}
              />
            </div>
          </div>
        </div>
        
        {channel.enabled && (
          <button
            onClick={testChannel}
            disabled={isTesting}
            className="ml-4 p-2 rounded-lg bg-[#e5e5e7] hover:bg-[#d2d2d7] disabled:opacity-50 transition-colors"
          >
            {isTesting ? (
              <Loader2 className="w-4 h-4 animate-spin text-[#0A84FF]" />
            ) : (
              <Play className="w-4 h-4 text-[#6e6e73]" />
            )}
          </button>
        )}
      </div>
      
      {showGuide && guideContent && (
        <div className="mt-3 p-3 rounded-lg bg-[#e5e5e7] text-sm text-[#1d1d1f]">
          <div className="font-medium mb-1 text-[#0A84FF]">{t.setupGuide}</div>
          <div className="whitespace-pre-line">{guideContent}</div>
        </div>
      )}
      
      {showDetails && channel.enabled && (
        <div className="mt-3 space-y-2 pl-13">
          {channelOption.configFields.map(field => (
            <div key={field.name} className="space-y-1">
              <label className="text-xs text-[#86868b] flex items-center gap-1">
                {getChannelConfigFieldLabel(field, language)}{field.required && '*'}
                {field.name === 'webhookUrl' && (
                  <span className="relative group">
                    <Eye className="w-3 h-3 text-[#aeaeb2]" />
                    <span className="absolute bottom-full left-1/2 transform -translate-x-1/2 mb-2 hidden group-hover:block bg-[#1d1d1f] text-white text-xs rounded px-2 py-1 w-48 z-10">
                      {t.webhookUrlTooltip}
                    </span>
                  </span>
                )}
              </label>
              <input
                type={field.type === 'password' ? 'password' : 'text'}
                value={channel.config[field.name] || ''}
                onChange={(e) => onConfigChange(channel.id, field.name, e.target.value)}
                placeholder={getChannelConfigFieldPlaceholder(field, language)}
                className="w-full px-3 py-2 input-apple text-sm text-[#1d1d1f]"
              />
            </div>
          ))}
        </div>
      )}
      
      {testResult && (
        <div className={`mt-3 p-3 rounded-lg text-sm ${
          testResult.success 
            ? 'bg-[#e5f5e8] text-[#30D158]' 
            : 'bg-[#ffe5e5] text-[#FF453A]'
        }`}>
          {testResult.message}
        </div>
      )}
    </div>
  )
}
